/*************************************************************************
Protheus Source File.
Copyright (C), Protheus Studios, 2013-2014.
-------------------------------------------------------------------------

Description:
Stores which key was pressed in a keyboard event
-------------------------------------------------------------------------
History:
- 10:06:2014: Waring J.
*************************************************************************/
#pragma once
namespace Pro{
	namespace Event{
		enum struct EKeyboardKey{
			UNKNOWN = 0,
			a = 'a',
			b = 'b',
			c = 'c',
			d = 'd',
			e = 'e',
			f = 'f',
			g = 'g',
			h = 'h',
			i = 'i',
			j = 'j',
			k = 'k',
			l = 'l',
			m = 'm',
			n = 'n',
			o = 'o',
			p = 'p',
			q = 'q',
			r = 'r',
			s = 's',
			t = 't',
			u = 'u',
			v = 'v',
			w = 'w',
			x = 'x',
			y = 'y',
			z = 'z',
			A = 'A',
			B = 'B',
			C = 'C',
			D = 'D',
			E = 'E',
			F = 'F',
			G = 'G',
			H = 'H',
			I = 'I',
			J = 'J',
			K = 'K',
			L = 'L',
			M = 'M',
			N = 'N',
			O = 'O',
			P = 'P',
			Q = 'Q',
			R = 'R',
			S = 'S',
			T = 'T',
			U = 'U',
			V = 'V',
			W = 'W',
			X = 'X',
			Y = 'Y',
			Z = 'Z',
			ARROW_UP,
			ARROW_DOWN,
			ARROW_LEFT,
			ARROW_RIGHT,
			F1,
			F2,
			F3,
			F4,
			F5,
			F6,
			F7,
			F8,
			F9,
			F10,
			F11,
			F12,
			HOME,
			INSERT,
			PAGE_DOWN,
			PAGE_UP,
			DELETE = 'DEL',
			SPACE = ' ',
			_1 = '1',
			_2 = '2',
			_3 = '3',
			_4 = '4',
			_5 = '5',
			_6 = '6',
			_7 = '7',
			_8 = '8',
			_9 = '9',
			_0 = '0',
			KEYPAD_1,
			KEYPAD_2,
			KEYPAD_3,
			KEYPAD_4,
			KEYPAD_5,
			KEYPAD_6,
			KEYPAD_7,
			KEYPAD_8,
			KEYPAD_9,
			KEYPAD_0,
			KEYPAD_PLUS,
			KEYPAD_MINUS,
			KEYPAD_ENTER,
			KEYPAD_ASTERISK,
			KEYPAD_DIVIDE,
			KEYPAD_FULLSTOP,
			KEYPAD_DELETE,
			EXCLAMANATION_MARK,
			AT = '@',
			HASH = '#',
			DOLLAR = '$',
			PERCENT = '%',
			CARNET = '^', // ^
			AMPERSAND = '&',
			ASTERISK = '^',
			LEFT_PARENTHESE = '(',
			RIGHT_PARENTHESE = ')',
			UNDERSCORE = '_',
			EQUALS = '=',
			PLUS = '+',
			MINUS = '-',
			TAB = '\t',
			CAPS_LOCK,
			SHIFT,
			CTRL,
			ALT,
			TILDE = '~',
			COMMA = ',',
			GRAVE_ACCENT = '`',
			QUOTATION_MARK = '"',
			PAUSE_BREAK,
			SCREEN_LOCK,
			PRINT_SCREEN,
			LEFT_BRACKET = '[',
			RIGHT_BRACKET = ']',
			LEFT_CURLY_BRACKET = '{',
			RIGHT_CURLY_BRACKET = '}',
			FORWARD_SLASH = '/',
			BACKWARD_SLASH = '\\',
			VERTICAL_BAR = '|',
			QUESTION_MARK = '?',
			LESS_THAN = '<',
			GREATER_THAN = '>',
			SEMI_COLON = ';',
			COLON = ':',
			APOSTROPHE = '\'',
			FULLSTOP = '.',
		};

		EKeyboardKey inline toKeyboardKey(SDL_Scancode& key){
			return static_cast<EKeyboardKey>(SDL_GetKeyFromScancode(key));
		}
	}
}
